[toolchain]
channel = "1.84.1"
components = [
    "clippy",
    "rustfmt",
    "rust-src",
    "rust-analyzer",
    "llvm-tools-preview",
]
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]
profile = "minimal"
