[toolchain]
channel = "1.88.0"
components = ["clippy", "rustfmt", "rust-src", "rust-analyzer", "llvm-tools-preview"]
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]
profile = "minimal"
