[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
xflags = "0.3.2"
polkadot-sdk = { workspace = true, features = ["std", "sp-keyring"] }
tempfile = "3.14.0"
serde_json = { version = "1", features = ["arbitrary_precision"] }
