[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
xflags = "0.3.2"
polkadot-sdk = { workspace = true, features = [
  "experimental",
  "runtime",
  "std",
] }
tempfile = "3.14.0"
