
//! Autogenerated weights for `pallet_emission0`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2025-05-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `NicosiPoneXSMax.localdomain`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/torus-node
// benchmark
// pallet
// --pallet
// pallet_emission0
// --chain
// dev
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/emission0/src/weights.rs
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::{
    frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}},
    *,
};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_emission0`.
pub trait WeightInfo {
	fn set_weights() -> Weight;
	fn delegate_weight_control() -> Weight;
	fn regain_weight_control() -> Weight;
}

/// Weights for `pallet_emission0` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Governance::Allocators` (r:1 w:0)
	/// Proof: `Governance::Allocators` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Emission0::WeightControlDelegation` (r:1 w:0)
	/// Proof: `Emission0::WeightControlDelegation` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Torus0::Agents` (r:2 w:0)
	/// Proof: `Torus0::Agents` (`max_values`: None, `max_size`: Some(857), added: 3332, mode: `MaxEncodedLen`)
	/// Storage: `Torus0::StakedBy` (r:2 w:0)
	/// Proof: `Torus0::StakedBy` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Torus0::MinValidatorStake` (r:1 w:0)
	/// Proof: `Torus0::MinValidatorStake` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Emission0::ConsensusMembers` (r:1 w:1)
	/// Proof: `Emission0::ConsensusMembers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn set_weights() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `515`
		//  Estimated: `7654`
		// Minimum execution time: 28_000_000 picoseconds.
		Weight::from_parts(28_000_000, 7654)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Torus0::Agents` (r:2 w:0)
	/// Proof: `Torus0::Agents` (`max_values`: None, `max_size`: Some(857), added: 3332, mode: `MaxEncodedLen`)
	/// Storage: `Governance::Allocators` (r:1 w:0)
	/// Proof: `Governance::Allocators` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Emission0::WeightControlDelegation` (r:0 w:1)
	/// Proof: `Emission0::WeightControlDelegation` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn delegate_weight_control() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `230`
		//  Estimated: `7654`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(17_000_000, 7654)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::Allocators` (r:1 w:0)
	/// Proof: `Governance::Allocators` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Emission0::WeightControlDelegation` (r:1 w:1)
	/// Proof: `Emission0::WeightControlDelegation` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn regain_weight_control() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `299`
		//  Estimated: `3529`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(13_000_000, 3529)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Governance::Allocators` (r:1 w:0)
	/// Proof: `Governance::Allocators` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Emission0::WeightControlDelegation` (r:1 w:0)
	/// Proof: `Emission0::WeightControlDelegation` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Torus0::Agents` (r:2 w:0)
	/// Proof: `Torus0::Agents` (`max_values`: None, `max_size`: Some(857), added: 3332, mode: `MaxEncodedLen`)
	/// Storage: `Torus0::StakedBy` (r:2 w:0)
	/// Proof: `Torus0::StakedBy` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Torus0::MinValidatorStake` (r:1 w:0)
	/// Proof: `Torus0::MinValidatorStake` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Emission0::ConsensusMembers` (r:1 w:1)
	/// Proof: `Emission0::ConsensusMembers` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn set_weights() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `515`
		//  Estimated: `7654`
		// Minimum execution time: 28_000_000 picoseconds.
		Weight::from_parts(28_000_000, 7654)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Torus0::Agents` (r:2 w:0)
	/// Proof: `Torus0::Agents` (`max_values`: None, `max_size`: Some(857), added: 3332, mode: `MaxEncodedLen`)
	/// Storage: `Governance::Allocators` (r:1 w:0)
	/// Proof: `Governance::Allocators` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Emission0::WeightControlDelegation` (r:0 w:1)
	/// Proof: `Emission0::WeightControlDelegation` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn delegate_weight_control() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `230`
		//  Estimated: `7654`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(17_000_000, 7654)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Governance::Allocators` (r:1 w:0)
	/// Proof: `Governance::Allocators` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Emission0::WeightControlDelegation` (r:1 w:1)
	/// Proof: `Emission0::WeightControlDelegation` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn regain_weight_control() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `299`
		//  Estimated: `3529`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(13_000_000, 3529)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
