#!/bin/bash

echo "Checking for formatting issues..."

HAS_ISSUES=0
for file in $(git diff --name-only --staged); do
    if [[ $file == *.rs ]]; then
      if ! cargo fmt --check -- $file; then
          HAS_ISSUES=1
      fi
    fi
done

if [ $HAS_ISSUES -eq 0 ]; then
    exit 0
fi

echo ". Your code has formatting issues in files listed above."
exit 1
