
//! Autogenerated weights for `pallet_permission0`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2025-06-10, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Luizs-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/torus-node
// benchmark
// pallet
// --pallet
// pallet_permission0
// --chain
// dev
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/permission0/src/weights.rs
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::{
    frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}},
    *,
};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_permission0`.
pub trait WeightInfo {
	fn grant_emission_permission() -> Weight;
	fn revoke_permission() -> Weight;
	fn execute_permission() -> Weight;
	fn toggle_permission_accumulation() -> Weight;
	fn enforcement_execute_permission() -> Weight;
	fn set_enforcement_authority() -> Weight;
	fn grant_curator_permission() -> Weight;
}

/// Weights for `pallet_permission0` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Torus0::Agents` (r:3 w:0)
	/// Proof: `Torus0::Agents` (`max_values`: None, `max_size`: Some(857), added: 3332, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::AccumulatedStreamAmounts` (r:1 w:1)
	/// Proof: `Permission0::AccumulatedStreamAmounts` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::Permissions` (r:1 w:1)
	/// Proof: `Permission0::Permissions` (`max_values`: None, `max_size`: Some(7535), added: 10010, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::PermissionsByParticipants` (r:1 w:1)
	/// Proof: `Permission0::PermissionsByParticipants` (`max_values`: None, `max_size`: Some(3266), added: 5741, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::PermissionsByGrantor` (r:1 w:1)
	/// Proof: `Permission0::PermissionsByGrantor` (`max_values`: None, `max_size`: Some(3234), added: 5709, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::PermissionsByGrantee` (r:1 w:1)
	/// Proof: `Permission0::PermissionsByGrantee` (`max_values`: None, `max_size`: Some(3234), added: 5709, mode: `MaxEncodedLen`)
	fn grant_emission_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `279`
		//  Estimated: `11000`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(36_000_000, 11000)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Permission0::Permissions` (r:1 w:1)
	/// Proof: `Permission0::Permissions` (`max_values`: None, `max_size`: Some(7535), added: 10010, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::PermissionsByParticipants` (r:1 w:1)
	/// Proof: `Permission0::PermissionsByParticipants` (`max_values`: None, `max_size`: Some(3266), added: 5741, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::PermissionsByGrantor` (r:1 w:1)
	/// Proof: `Permission0::PermissionsByGrantor` (`max_values`: None, `max_size`: Some(3234), added: 5709, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::PermissionsByGrantee` (r:1 w:1)
	/// Proof: `Permission0::PermissionsByGrantee` (`max_values`: None, `max_size`: Some(3234), added: 5709, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::AccumulatedStreamAmounts` (r:0 w:1)
	/// Proof: `Permission0::AccumulatedStreamAmounts` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::RevocationTracking` (r:0 w:1)
	/// Proof: `Permission0::RevocationTracking` (`max_values`: None, `max_size`: Some(353), added: 2828, mode: `MaxEncodedLen`)
	fn revoke_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `590`
		//  Estimated: `11000`
		// Minimum execution time: 31_000_000 picoseconds.
		Weight::from_parts(32_000_000, 11000)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Permission0::Permissions` (r:1 w:1)
	/// Proof: `Permission0::Permissions` (`max_values`: None, `max_size`: Some(7535), added: 10010, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::AccumulatedStreamAmounts` (r:2 w:1)
	/// Proof: `Permission0::AccumulatedStreamAmounts` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn execute_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `546`
		//  Estimated: `11000`
		// Minimum execution time: 41_000_000 picoseconds.
		Weight::from_parts(42_000_000, 11000)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Permission0::Permissions` (r:1 w:1)
	/// Proof: `Permission0::Permissions` (`max_values`: None, `max_size`: Some(7535), added: 10010, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::EnforcementTracking` (r:0 w:1)
	/// Proof: `Permission0::EnforcementTracking` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	fn toggle_permission_accumulation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `356`
		//  Estimated: `11000`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(15_000_000, 11000)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Permission0::Permissions` (r:1 w:1)
	/// Proof: `Permission0::Permissions` (`max_values`: None, `max_size`: Some(7535), added: 10010, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::EnforcementTracking` (r:1 w:1)
	/// Proof: `Permission0::EnforcementTracking` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::AccumulatedStreamAmounts` (r:2 w:1)
	/// Proof: `Permission0::AccumulatedStreamAmounts` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn enforcement_execute_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `583`
		//  Estimated: `11000`
		// Minimum execution time: 47_000_000 picoseconds.
		Weight::from_parts(48_000_000, 11000)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Permission0::Permissions` (r:1 w:1)
	/// Proof: `Permission0::Permissions` (`max_values`: None, `max_size`: Some(7535), added: 10010, mode: `MaxEncodedLen`)
	fn set_enforcement_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `356`
		//  Estimated: `11000`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(17_000_000, 11000)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Permission0::PermissionsByGrantee` (r:1 w:1)
	/// Proof: `Permission0::PermissionsByGrantee` (`max_values`: None, `max_size`: Some(3234), added: 5709, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::Permissions` (r:1 w:1)
	/// Proof: `Permission0::Permissions` (`max_values`: None, `max_size`: Some(7535), added: 10010, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::PermissionsByParticipants` (r:1 w:1)
	/// Proof: `Permission0::PermissionsByParticipants` (`max_values`: None, `max_size`: Some(3266), added: 5741, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::PermissionsByGrantor` (r:1 w:1)
	/// Proof: `Permission0::PermissionsByGrantor` (`max_values`: None, `max_size`: Some(3234), added: 5709, mode: `MaxEncodedLen`)
	fn grant_curator_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `11000`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(19_000_000, 11000)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Torus0::Agents` (r:3 w:0)
	/// Proof: `Torus0::Agents` (`max_values`: None, `max_size`: Some(857), added: 3332, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::AccumulatedStreamAmounts` (r:1 w:1)
	/// Proof: `Permission0::AccumulatedStreamAmounts` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::Permissions` (r:1 w:1)
	/// Proof: `Permission0::Permissions` (`max_values`: None, `max_size`: Some(7535), added: 10010, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::PermissionsByParticipants` (r:1 w:1)
	/// Proof: `Permission0::PermissionsByParticipants` (`max_values`: None, `max_size`: Some(3266), added: 5741, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::PermissionsByGrantor` (r:1 w:1)
	/// Proof: `Permission0::PermissionsByGrantor` (`max_values`: None, `max_size`: Some(3234), added: 5709, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::PermissionsByGrantee` (r:1 w:1)
	/// Proof: `Permission0::PermissionsByGrantee` (`max_values`: None, `max_size`: Some(3234), added: 5709, mode: `MaxEncodedLen`)
	fn grant_emission_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `279`
		//  Estimated: `11000`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(36_000_000, 11000)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `Permission0::Permissions` (r:1 w:1)
	/// Proof: `Permission0::Permissions` (`max_values`: None, `max_size`: Some(7535), added: 10010, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::PermissionsByParticipants` (r:1 w:1)
	/// Proof: `Permission0::PermissionsByParticipants` (`max_values`: None, `max_size`: Some(3266), added: 5741, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::PermissionsByGrantor` (r:1 w:1)
	/// Proof: `Permission0::PermissionsByGrantor` (`max_values`: None, `max_size`: Some(3234), added: 5709, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::PermissionsByGrantee` (r:1 w:1)
	/// Proof: `Permission0::PermissionsByGrantee` (`max_values`: None, `max_size`: Some(3234), added: 5709, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::AccumulatedStreamAmounts` (r:0 w:1)
	/// Proof: `Permission0::AccumulatedStreamAmounts` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::RevocationTracking` (r:0 w:1)
	/// Proof: `Permission0::RevocationTracking` (`max_values`: None, `max_size`: Some(353), added: 2828, mode: `MaxEncodedLen`)
	fn revoke_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `590`
		//  Estimated: `11000`
		// Minimum execution time: 31_000_000 picoseconds.
		Weight::from_parts(32_000_000, 11000)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `Permission0::Permissions` (r:1 w:1)
	/// Proof: `Permission0::Permissions` (`max_values`: None, `max_size`: Some(7535), added: 10010, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::AccumulatedStreamAmounts` (r:2 w:1)
	/// Proof: `Permission0::AccumulatedStreamAmounts` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn execute_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `546`
		//  Estimated: `11000`
		// Minimum execution time: 41_000_000 picoseconds.
		Weight::from_parts(42_000_000, 11000)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Permission0::Permissions` (r:1 w:1)
	/// Proof: `Permission0::Permissions` (`max_values`: None, `max_size`: Some(7535), added: 10010, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::EnforcementTracking` (r:0 w:1)
	/// Proof: `Permission0::EnforcementTracking` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	fn toggle_permission_accumulation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `356`
		//  Estimated: `11000`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(15_000_000, 11000)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Permission0::Permissions` (r:1 w:1)
	/// Proof: `Permission0::Permissions` (`max_values`: None, `max_size`: Some(7535), added: 10010, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::EnforcementTracking` (r:1 w:1)
	/// Proof: `Permission0::EnforcementTracking` (`max_values`: None, `max_size`: Some(355), added: 2830, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::AccumulatedStreamAmounts` (r:2 w:1)
	/// Proof: `Permission0::AccumulatedStreamAmounts` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn enforcement_execute_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `583`
		//  Estimated: `11000`
		// Minimum execution time: 47_000_000 picoseconds.
		Weight::from_parts(48_000_000, 11000)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Permission0::Permissions` (r:1 w:1)
	/// Proof: `Permission0::Permissions` (`max_values`: None, `max_size`: Some(7535), added: 10010, mode: `MaxEncodedLen`)
	fn set_enforcement_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `356`
		//  Estimated: `11000`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(17_000_000, 11000)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Permission0::PermissionsByGrantee` (r:1 w:1)
	/// Proof: `Permission0::PermissionsByGrantee` (`max_values`: None, `max_size`: Some(3234), added: 5709, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::Permissions` (r:1 w:1)
	/// Proof: `Permission0::Permissions` (`max_values`: None, `max_size`: Some(7535), added: 10010, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::PermissionsByParticipants` (r:1 w:1)
	/// Proof: `Permission0::PermissionsByParticipants` (`max_values`: None, `max_size`: Some(3266), added: 5741, mode: `MaxEncodedLen`)
	/// Storage: `Permission0::PermissionsByGrantor` (r:1 w:1)
	/// Proof: `Permission0::PermissionsByGrantor` (`max_values`: None, `max_size`: Some(3234), added: 5709, mode: `MaxEncodedLen`)
	fn grant_curator_permission() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `11000`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(19_000_000, 11000)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
}
