name: Docker build and push xtask cli tool

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'xtask/**'
      - '.github/workflows/build-docker-xtask.yml'
      - 'docker/xtask.dockerfile'
    
jobs:
  docker:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/torus-xtask
          tags: |
            type=sha,prefix=,enable=true
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./docker/xtask.dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
