name: Build and push Docker image

on:
  push:
    branches: [main, testnet, github-ci-test]
    tags:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-n-push:
    permissions: write-all
    runs-on: ubuntu-22.04-32core-karl
    steps:
      - uses: actions/checkout@v3

      - id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare build
        id: prepare
        run: |
          echo "SANITIZED_REF=$(echo "${GITHUB_REF##*/}" | tr '/' '-')" >> $GITHUB_ENV
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}"     > "$HOME/aws-key-id.txt"
          echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}" > "$HOME/aws-secret-key.txt"
          echo "AWS_ACCESS_KEY_ID_PATH=$HOME/aws-key-id.txt"         >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY_PATH=$HOME/aws-secret-key.txt" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: docker/node.dockerfile
          secret-files: |
            aws-key-id=${{ env.AWS_ACCESS_KEY_ID_PATH }}
            aws-secret-key=${{ env.AWS_SECRET_ACCESS_KEY_PATH }}
          build-args: |
            SCCACHE_BUCKET=torus-substrate-cache
            SCCACHE_ENDPOINT=${{ secrets.SCCACHE_ENDPOINT }}
            SCCACHE_REGION=auto
          tags: |
            ghcr.io/renlabs-dev/torus-substrate:${{ steps.commit.outputs.short }}
            ghcr.io/renlabs-dev/torus-substrate:${{ env.SANITIZED_REF }}
