name: Build and push Docker image

on:
  push:
    branches: [main, github-ci-test]
    tags:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-n-push:
    permissions: write-all
    runs-on: ubuntu-22.04-32core-karl
    steps:
      - uses: actions/checkout@v3

      - id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sanitize Ref Name
        id: sanitize_ref
        run: echo "SANITIZED_REF=$(echo "${GITHUB_REF##*/}" | tr '/' '-')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            SCCACHE_BUCKET=torus-substrate-cache
            SCCACHE_ENDPOINT=${{ secrets.SCCACHE_ENDPOINT }}
            SCCACHE_REGION=auto
          file: docker/node.dockerfile
          tags: |
            ghcr.io/renlabs-dev/torus-substrate:${{ steps.commit.outputs.short }}
            ghcr.io/renlabs-dev/torus-substrate:${{ env.SANITIZED_REF }}
