name: Build Torus Runtime

on:
  push:
    tags: "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04-32core-karl

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install Rust toolchain
        run: |
          rustup set profile minimal
          rustup show

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: 3.20.1
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build runtime
        run: |
          cargo build --release --timings --package torus-runtime

          export SHA256SUM=$(sha256sum target/release/wbuild/torus-runtime/torus_runtime.compact.compressed.wasm | cut -d ' ' -f1)
          echo Hash of compact and compressed WASM: $SHA256SUM

          mkdir out
          mv target/release/wbuild/torus-runtime/torus_runtime.compact.compressed.wasm out/
          touch out/$SHA256SUM

      - uses: actions/upload-artifact@v4
        with:
          name: torus_runtime.compact.compressed
          path: out/
          if-no-files-found: error
          overwrite: true

      - uses: actions/upload-artifact@v4
        with:
          name: torus-runtime-timings
          path: target/cargo-timings/cargo-timing.html
          overwrite: true
